---
- name: Apache2 install
  hosts: web
  tasks:
  - name: Install_Apache
    apt:
      name: apache2
      state: present

  - name: enable apache2
    service:
      name: apache2
      enabled: yes

  - name: checking service status
    command: systemctl status "{{ item }}"
    with_items:
    - apache2
    register: result
    changed_when: False
  - name: showing report
    debug:
      var: result

  - name: Create index.html
    copy:
      dest: "/var/www/html/index.html"
      content: |
        Welcome to my
        web server
  - name: Enable traffic in default zone for http service
    ansible.builtin.iptables:
      chain: INPUT
      protocol: tcp
      destination_port: 80
      jump: ACCEPT
      
