---
- name: Apache2 install
  hosts: web
  tasks:
  - name: Uninstall Apache
    apt:
      name: apache2
      state: absent
      purge: yes
      force: yes

  - name: Delete index.html
    file:
      state: absent
      path: "/var/www/html/index.html"

  - name: Disable traffic in default zone for http service
    ansible.builtin.iptables:
      chain: INPUT
      protocol: tcp
      destination_port: 80
      jump: DROP
