---
# tasks file for site.apache

- name: Include OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"

- name: Apache package instalation
  ansible.builtin.package:
    name: "{{ apache_packages }}"
    state: present

- name: Enable {{  apache_service }}
  service:
    name: "{{  apache_service }}"
    state: started
    enabled: yes

- name: Checking Service Status
  command: systemctl status {{  apache_service }}
  register: result
  changed_when: False

- name: showing report
  debug:
    var: result
