---
- name: Install Httpd
  yum:
    name: httpd
    state: present

- name: Enable Httpd
  service:
    name: httpd
    enabled: yes

- name: Checking Service Status
  command: systemctl status httpd
  register: result
  changed_when: False
